### ISSUE TITLE
Violation of Github Terms (K): Issue tracking without content

### ISSUE THREAD

**Issue by gardner** [kitten/dank-mono#17]
Abusing github by hosting your advertisement material here and using their bug tracking system while not actually hosting a project on github violates the [terms of service](https://help.github.com/articles/github-terms-of-service/) and is a pretty uncool thing to do. You are taking resources from a community and giving nothing back.

If you want to open source your project then please host is on github. If you want to advertise and sell your proprietary product then you should pay for your own issue tracker and hosting.

**Comment by kitten** [comment]
Thanks for raising this, I wasn't aware of those specific restrictions. That being said, I do believe I am giving enough resources back to GitHub regarding that part, however it'd indeed make sense to host a dedicated issue tracker some place else.

(Relevant section if someone else is interested: https://help.github.com/articles/github-terms-of-service/#2-github-repositories)

> You may include static images, links, and promotional text in the README documents associated with your repositories, but they must be related to the project you are hosting on GitHub.

I'll probably follow this up with GitHub for future reference, since I'd be interested to find out how they'd treat the specifics of the circumstances of this repo. Either way, I'll search an alternative platform to host the issue tracking on.

**Comment by kitten** [comment]
Just migrated all pending issues to Spectrum https://spectrum.chat/dank-mono

Thanks again for raising this! On second thought Spectrum is actually a better fit even
