### ISSUE TITLE
Consider making regular "f" less stand out

### ISSUE THREAD

**Issue by narqo** [kitten/dank-mono#5]
In the [blog post][1] you specifically mentioned your work on the "f" glyph. While I appreciate it, I can't make myself stop reading everything that starts with "f", as being ƒ-something. 

So instead of `fmt`, my brain reads `ƒ-mt`. `ƒ-alse` instead of `false`.

I'm far from font design, but take a look at the following line written in regular glyphs

<img width="288" alt="screen shot 2018-04-30 at 12 54 34" src="https://user-images.githubusercontent.com/88045/39424239-eb6d794a-4c75-11e8-8465-da28b14005b2.png">

Just because the "f" is so distinctive, the whole base line looks displaced and I believe this might be the source of my problem.

[1]: https://medium.com/@philpl/what-sets-dank-mono-apart-1bbdc1cc3cbd

**Comment by spences10** [comment]
I ❤️ this feature too and it's one of the standout features of Dank Mono

**Comment by kitten** [comment]
Fixed in v0.460

![group 3x](https://user-images.githubusercontent.com/2041385/39452502-5d940468-4cca-11e8-8c38-7404b38995ed.png)
<img width="527" alt="screen shot 2018-04-30 at 22 25 18" src="https://user-images.githubusercontent.com/2041385/39452503-5db5cc2e-4cca-11e8-95d6-4609a559deec.png">
<img width="1000" alt="screen shot 2018-04-30 at 22 34 05" src="https://user-images.githubusercontent.com/2041385/39452504-5dd477d2-4cca-11e8-91be-e0bfaebc252a.png">
